<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>rapport</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="rapport_files/libs/clipboard/clipboard.min.js"></script>
<script src="rapport_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="rapport_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="rapport_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="rapport_files/libs/quarto-html/popper.min.js"></script>
<script src="rapport_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="rapport_files/libs/quarto-html/anchor.min.js"></script>
<link href="rapport_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="rapport_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="rapport_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="rapport_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="rapport_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">rapport</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="case-analysera-e-handel" class="level1">
<h1><strong>Case: Analysera E-handel</strong></h1>
<section id="mål-och-syfte" class="level4">
<h4 class="anchored" data-anchor-id="mål-och-syfte"><strong>Mål och syfte:</strong></h4>
<p>Företaget vill få bättre förståelse för verksamheten och vill använda data som underlag för beslut. Vi ska genomföra en tydlig dataanalys i R och använda datat för att besvara ett antal relevanta frågeställningar. Arbetet innehåller följande fem moment:</p>
<ul>
<li>Dataförståelse</li>
<li>Datastädning och förberedelse</li>
<li>Statistiska sammanfattningar</li>
<li>Visualiseringar</li>
<li>Tolkningar och slutsatser</li>
</ul>
</section>
<section id="dataförståelse" class="level4">
<h4 class="anchored" data-anchor-id="dataförståelse"><strong>Dataförståelse</strong></h4>
<p>Datasetet innehåller <strong>1 000 observationer</strong> och <strong>16 variabler</strong>. Datat omfattar information om ordrar, kunder, produkter, rabatter, leveranser och returer.</p>
<p><strong>Kategoriska variabler</strong>: order_id, order_date, customer_id, customer_segment, customer_type, region, city, product_category, product_subcategory, payment_method, campaign_source, returned</p>
<p><strong>Numeriska variabler</strong>: quantity, unit_price, discount_pct, shipping_days</p>
<p><strong>Datatyper som behöver justeras</strong></p>
<ul>
<li><p>order_date konverteras från text till datumformat</p></li>
<li><p>returned omvandlas till logisk variabel (TRUE/FALSE)</p></li>
</ul>
<p><strong>Saknade värden</strong></p>
<ul>
<li><p><strong>Explicita (NA)</strong>:</p>
<ul>
<li><p>discount_pct (27 st) - tolkas som 0</p></li>
<li><p>shipping_days (22 st) - lämnas som NA</p></li>
</ul></li>
<li><p><strong>Implicita (tomma värden)</strong>:</p>
<ul>
<li><p>city - omvandlas till NA</p></li>
<li><p>payment_method - omvandlas till NA</p></li>
<li><p>campaign_source - omvandlas till NA</p></li>
</ul></li>
</ul>
<p><strong>Datakvalitet</strong></p>
<p>Flera kategoriska variabler innehåller inkonsekvenser, t.ex.:</p>
<ul>
<li><p>stora/små bokstäver (“Stockholm”, “stockholm”)</p></li>
<li><p>extra mellanslag (“Gothenburg”)</p></li>
<li><p>olika stavningar (“PayPal”, “Paypal”)</p></li>
</ul>
<p>Dessa behöver standardiseras för korrekt analys.</p>
<p><strong>Viktiga variabler för analys</strong></p>
<ul>
<li><p><strong>Försäljning</strong>: quantity, unit_price, discount_pct</p></li>
<li><p><strong>Kund</strong>: customer_segment, customer_type</p></li>
<li><p><strong>Returer</strong>: returned</p></li>
<li><p><strong>Leverans</strong>: shipping_days</p></li>
<li><p><strong>Produkt</strong>: product_category</p></li>
<li><p><strong>Marknadsföring</strong>: campaign_source</p></li>
</ul>
</section>
<section id="datastädning-förberedelse" class="level4">
<h4 class="anchored" data-anchor-id="datastädning-förberedelse"><strong>Datastädning &amp; förberedelse</strong></h4>
<p>Rådatan städas enligt föregående avsnitts upptäckter och rekommendationer. Detta görs med hjälp av tidyverse-paketet tillsammans med Feature Engineering i en och samma pipe.</p>
<p><strong>Skapandet av nya variabler (Feature Engineering)</strong></p>
<p>Flertalet nya variabler skapas för att möjliggöra olika analyser.</p>
<p><strong>Ekonomiska nyckeltal</strong></p>
<ul>
<li><p><strong>order_value</strong>: bruttovärde (kvantitet * pris)</p></li>
<li><p><strong>price_after_discount</strong>: pris per enhet efter avdragen rabatt</p></li>
<li><p><strong>order_value_net</strong>: det faktiska totalbeloppet efter rabatt</p></li>
</ul>
<p><strong>Kategorisering</strong></p>
<ul>
<li><p><strong>discount_group</strong>: grupperar rabatter i kategorierna ”Ingen rabatt”, ”Låg”, ”Medium” och ”Hög” baserat på procentsatsen</p></li>
<li><p><strong>delivery_category</strong>: delar upp leveranstiden i ”Snabb” (≤ 2 dagar) eller ”Långsam”</p></li>
</ul>
<p><strong>Tidsdimension</strong></p>
<ul>
<li><strong>order_month</strong>: extraherar år och månad för att kunna följa trender över tid</li>
</ul>
<p>Den transformerade datan sparas i en ny variabel: data_clean</p>
</section>
<section id="valda-frågeställningar" class="level4">
<h4 class="anchored" data-anchor-id="valda-frågeställningar"><strong>Valda frågeställningar</strong></h4>
<p>Vi har valt ut tre stycken frågeställningar från den givna listan samt en egenformulerad.</p>
<ol type="1">
<li>Vilka produktkategorier verkar driva högst försäljning?</li>
<li>Hur skiljer sig ordervärde mellan olika kundsegment?</li>
<li>Finns det samband mellan rabatt och ordervärde?</li>
<li>Vilka produktkategorier har högst försäljning hos de olika kundsegmenten? (egen frågeställning)</li>
</ol>
<p>De valda frågeställningarna fokuserar på att analysera försäljning, vilket är företagets mest centrala funktion. Genom att undersöka vilka produktkategorier och kundsegment som driver högst försäljning kan företaget identifiera sina viktigaste intäktskällor.</p>
<p>Att analysera sambandet mellan rabatt och ordervärde kan ge insikter om kundernas köpbeteende och detta är viktigt för att kunna optimera prissättning och kampanjer.</p>
<p>Den egna frågeställningen valdes för att komplettera analysen och ge ytterligare förståelse för faktorer som kan påverka försäljningen. Tillsammans bidrar dessa frågeställningar till en helhetsbild av företagets försäljning och kundbeteende vilket kan användas som underlag för strategiska beslut.</p>
<p>Nedan följer en sammanfattning för varje vald frågeställning som inkluderar metod, resultat samt slutsatser och eventuella begränsningar.</p>
</section>
<section id="vilka-produktkategorier-verkar-driva-högst-försäljning" class="level4">
<h4 class="anchored" data-anchor-id="vilka-produktkategorier-verkar-driva-högst-försäljning"><strong>1. Vilka produktkategorier verkar driva högst försäljning?</strong></h4>
<p>För att besvara frågeställningen analyserades försäljningen per produktkategori. Ordervärdet beräknades baserat på antal, styckpris och rabatt, och därefter summerades försäljningen för varje kategori.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sales_by_category</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  product_category total_sales avg_sales median_sales n_orders
  &lt;chr&gt;                  &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;    &lt;int&gt;
1 Electronics          155811.     641.         450.       243
2 Home                  60569.     293.         143.       207
3 Sports                54312.     348.         219.       156
4 Fashion               32207.     137.         102.       235
5 Beauty                12156.      76.5         62.9      159</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>sales_by_category_viz</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rapport_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>orders_by_category_viz</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rapport_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Figur 1</strong> visar den totala försäljningen per produktkategori.</p>
<ul>
<li>Figuren visar tydligt att Electronics är den kategori som genererar mest försäljning, med en tydlig marginal till övriga kategorier.</li>
</ul>
<p><strong>Figur 2</strong> visar antal ordrar per produktkategori.</p>
<ul>
<li>Denna figur ger ytterligare förståelse för hur försäljningen uppstår. Kategorier som <strong>Fashion</strong> har många ordrar men lägre total försäljning, medan <strong>Electronics</strong> kombinerar både högt ordervärde och relativt många ordrar.</li>
</ul>
<p>Sammanfattningsvis visar analysen att <strong>Electronics</strong> är den produktkategori som driver högst försäljning. Detta beror sannolikt på en kombination av höga ordervärden och en relativt hög efterfrågan.</p>
<p>Analysen visar också att olika kategorier bidrar till försäljningen på olika sätt. Vissa kategorier drivs främst av höga priser per order, medan andra drivs av ett stort antal ordrar.</p>
<p>Resultaten kan användas som underlag för beslut kring exempelvis marknadsföring, lagerhållning och produktstrategi.</p>
<p>En begränsning i analysen är att den inte tar hänsyn till kostnader eller vinstmarginaler, vilket innebär att hög försäljning inte nödvändigtvis motsvarar hög lönsamhet.</p>
</section>
<section id="hur-skiljer-sig-ordervärde-mellan-olika-kundsegment" class="level4">
<h4 class="anchored" data-anchor-id="hur-skiljer-sig-ordervärde-mellan-olika-kundsegment"><strong>2. Hur skiljer sig ordervärde mellan olika kundsegment?</strong></h4>
<p>Skapade en sammanfattning av genomsnittligt och medianordervärde för varje kundsegment, samt antal ordrar och andel av totalen. Detta för att få en tydlig överblick över hur ordervärdet varierar mellan segmenten och hur stora de är i relation till varandra.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>data_clean_customer_segment</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  customer_segment count avg_order_value median share
  &lt;chr&gt;            &lt;int&gt;           &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 Small Business     302            346.   162. 0.302
2 Consumer           529            323.   161. 0.529
3 Corporate          169            236.   137. 0.169</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>order_value_by_segment_viz</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rapport_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Stapeldiagrammet visar det genomsnittliga ordervärdet per kundsegment. Diagrammet sorterades från lägst till högst för att tydliggöra skillnaderna mellan segmenten och göra det enkelt att jämföra deras relativa nivåer.</p>
<ul>
<li><p>Small Business har det högsta genomsnittliga ordervärdet, följt av Consumer, medan Corporate ligger tydligt lägst.</p></li>
<li><p>Skillnaden mellan högsta och lägsta segmentet är cirka 46,86%.</p></li>
</ul>
<p>Att Small Business har det högsta ordervärdet är inte oväntat, då mindre företag ofta gör större inköp per order jämfört med privatkunder.</p>
<p>Antalet observationer skiljer sig mellan segmenten, där Consumer står för den största andelen medan Corporate är betydligt mindre. Detta innebär att resultaten i högre grad påverkas av Consumer-segmentet, och att jämförelser mellan segment bör tolkas med viss försiktighet.</p>
</section>
<section id="finns-det-samband-mellan-rabatt-och-ordervärde" class="level4">
<h4 class="anchored" data-anchor-id="finns-det-samband-mellan-rabatt-och-ordervärde"><strong>3. Finns det samband mellan rabatt och ordervärde?</strong></h4>
<p>Skapade en sammanfattning över ordervärde och rabatt. Sammanfattningen svarar på frågor som vad är det genomsnittliga order/ rabattvärdet? Vad ligger medianen på i respektive kolumner? Och vad är det högsta rabatt/ ordervärdet?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>AOV_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Order_count Average_order_value Median_order_value Max_order_value
1        1000            315.0556           152.3285        2926.404
  Average_discount Median_discount Max_discount
1          0.06876           0.062        0.306</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>AOV_discount_viz</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rapport_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figuren visar ordervärde på x-axeln och rabatt på y-axeln, samt en trendlinje för att tydligare se om det verkar finnas ett samband.</p>
<p>Av vår figur kan vi inte se något tydligt linjärt samband mellan ordervärde och rabattmängd. Scatterplotten visar en plan linje vilket indikerar att ett högre ordervärde inte resulterar i en högre rabatt. Vid varje ordervärde(framförallt låga) finns det en stor variation i hur mycket rabatt kunderna fått och det går inte att se något tydligt mönster, vilket ger stöd åt tesen att det inte finns något samband mellan enbart dessa två variabler.</p>
<p>Fler variabler krävs för att förstår vad som påverkar rabattvärde. Extremvärden ger även en skev bild av meddelvärdet som inte motsvarar kunderas beteende. (Medelvärde -315, Median -152)</p>
</section>
<section id="vilka-produktkategorier-har-högst-försäljning-hos-de-olika-kundsegmenten" class="level4">
<h4 class="anchored" data-anchor-id="vilka-produktkategorier-har-högst-försäljning-hos-de-olika-kundsegmenten"><strong>4. Vilka produktkategorier har högst försäljning hos de olika kundsegmenten?</strong></h4>
<p>Skapade en sammanfattning av den totala nettoförsäljningen för varje produktkategori och kundsegment, tillsammans med antalet ordar, median och genomsnittligt ordervärde för att få en överblick och kunna jämföra försäljningen mellan de olika kategorierna.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>sales_summary_04</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 6
   product_category customer_segment total_rev num_orders avg_order mdn_order
   &lt;chr&gt;            &lt;chr&gt;                &lt;dbl&gt;      &lt;int&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 Electronics      Consumer            86538.        133     651.      450. 
 2 Sports           Consumer            31029.         81     383.      237. 
 3 Home             Consumer            29793.        105     284.      143. 
 4 Fashion          Consumer            17206.        130     132.      101. 
 5 Beauty           Consumer             6115.         80      76.4      63.4
 6 Electronics      Corporate           18761.         37     507.      404. 
 7 Sports           Corporate            6327.         27     234.      186. 
 8 Fashion          Corporate            6251.         44     142.      114. 
 9 Home             Corporate            6063.         29     209.      102. 
10 Beauty           Corporate            2415.         32      75.5      55.7
11 Electronics      Small Business      50512.         73     692.      486. 
12 Home             Small Business      24713.         73     339.      159. 
13 Sports           Small Business      16956.         48     353.      236. 
14 Fashion          Small Business       8750.         61     143.       99.2
15 Beauty           Small Business       3626.         47      77.2      63.6</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>total_sales_viz_stacked</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rapport_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>total_sales_viz</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rapport_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Den första figuren visar den totala försäljningen för varje kundsegment, uppdelat i produktkategorier. Den andra figuren visar andelen av försäljning per produktkategori och kundsegment, från 0-100%, och ger också en tydlig bild hur de förhåller sig till varandra.</p>
<ul>
<li><p><strong>Electronics</strong> är den klart starkaste kategorin bland alla typer av kunder.</p></li>
<li><p>Det motsatta gäller <strong>Beauty</strong>, det är den klart minsta kategorin.</p></li>
<li><p>Tydligaste skillnaderna ses bland <strong>Home</strong>- och <strong>Fashion-produkter</strong> mellan <strong>Small Business</strong> och <strong>Corporate</strong>.</p></li>
<li><p><strong>Consumer</strong> står för den absolut största totala försäljningen, medan <strong>Corporate</strong> står för en betydligt mindre del.</p></li>
</ul>
<p>Analysen kan användas för att optimera riktad marknadsföring beroende på typ av kund, men som i tidigare analys säger den inget om eventuell vinstmarginal.</p>
</section>
<section id="slutsats-och-sammanfattning" class="level4">
<h4 class="anchored" data-anchor-id="slutsats-och-sammanfattning"><strong>Slutsats och sammanfattning</strong></h4>
<p>Analysen visar att försäljningen i stor utsträckning drivs av specifika produktkategorier och kundsegment, snarare än rabatter. Med hjälp av våra fyra frågeställningar kunde vi få en tydlig inblick i köpmönster hos olika typer av kunder.</p>
<ul>
<li><p><strong>Electronics</strong> har högst försäljning med stor marginal, följt av <strong>Home</strong> och <strong>Sports</strong>, vilket visar att dessa kategorier är företagets viktigaste intäktsdrivare.</p></li>
<li><p><strong>Electronics</strong> är också den klart starkaste kategorin bland alla typer av kunder, vilket tyder på en stabil efterfrågan oavsett kundsegment. De tydligaste skillnaderna ses bland <strong>Home</strong>- och <strong>Fashion-produkter</strong> mellan <strong>Small Business</strong> och <strong>Corporate</strong>, vilket indikerar att olika kundgrupper bidrar olika mycket till försäljningen beroende på produktkategori.</p></li>
<li><p><strong>Small Business</strong> har det högsta genomsnittliga ordervärdet, följt av <strong>Consumer</strong>, medan <strong>Corporate</strong> ligger tydligt lägst. Detta innebär att <strong>Small Business</strong> är en särskilt värdefull kundgrupp ur ett försäljningsperspektiv då de bidrar mest per köp.</p></li>
<li><p><strong>Inget</strong> tydligt samband mellan rabatt och ordervärde, vilket tyder på att rabatter inte är en avgörande faktor för att öka försäljningen i detta dataset.</p></li>
</ul>
<p>Det är dock viktigt att notera att hög försäljning inte nödvändigtvis innebär hög lönsamhet, vilket gör det relevant att i framtida analyser även inkludera vinstmarginaler.</p>
<p>Nästa steg kan vara att göra djupare analys kring köpmönster runt kampanjer (rabatt) och tidsanalyser för att identifiera när och varför försäljningen är som högst. Detta kan ge ytterligare insikter om hur försäljningen kan optimeras.</p>
<p>Resultaten visar att företaget bör fokusera på att stärka de mest intäktsdrivande produktkategorierna samt rikta sina insatser mot kundsegment med högt ordervärde. Detta kan bidra till att maximera försäljningen snarare än att enbart öka volymen genom rabatter.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>